### ISSUE TITLE
Update checker fails because target file is missing.

### ISSUE THREAD

**Issue by Claycorp** [feldim2425/MoreOverlays#14]
http://pastebin.com/5aAHw1L7

**Comment by feldim2425** [comment]
Yes I derped with the Update JSON. But I sayed in the comment of the latest update (on Curse), that I will fix it in the next version.

And btw. your pastebin link is deleted :D

**Comment by feldim2425** [comment]
I already fixed it in this commit: b95d85cc57c27c9f0f66ea7e830c504af5229a4e

I didn't know that gist-links show the old version of the file ans not the current verson. Derp :D

**Comment by Claycorp** [comment]
I see you changed it after uploading V1.6. Not the best idea to change things that are relied on like that after you just pushed a build out...

**Comment by feldim2425** [comment]
It is will also not work with update 1.6 -> 1.7. Because I just realized that issue when I already uploadet V1.6 and it was too late to change it.
In the version 1.7 the url for the json will be fixed and it can check for updates.
But uploading a new Version just to fix update json doesn't make much sense.

EDIT: The reason why I didn't realized the problem is that I can only change the JSON after uplading the new Version. If I change it before the Version is out people will get a update message when there is no new Version.
