### ISSUE TITLE
[1.10.2][MO 1.7] Light and chunk overlay incompatible with F1 (Hide hud)

### ISSUE THREAD

**Issue by Aedda** [feldim2425/MoreOverlays#17]
Turn on light overlays (default F7), or chunk boundaries (default F9), then turn off hud display (default F1) and the screen becomes intensely dark.

https://i.imgur.com/HSTyUbS.png

This is noon on a sunny day:
https://i.imgur.com/Q7VefMG.png

**Comment by feldim2425** [comment]
Like #12 . I don't know why this destroys the lightning. I can't reproduce it. It is either incompatibility with another Mod or depending on the System or the GPU.

**Comment by Vectrobe** [comment]
If you still see this, try disabling the FBO in the minecraft settings file via 'fboEnable', set it to false.
it appears that the FBO triangles are getting modified somehow, possibly a legacy lighting call or alpha settings...

**Comment by Vectrobe** [comment]
On my client the sky darkens when HUD is off and either of the overlays are enabled, everything else is fine. I have the FBO off already, I bet without looking at the overlay code it's a GL light call.

**Comment by feldim2425** [comment]
From my tests it works in vanilla without anything installes except Forge, JEI and MoreOverlays.
So I guess even if MoreOverlays makes the sky dark, some other mod has to do some wierd renering stuff and break the rendering system. I guess OptiFine but I'm not sure.  But I have to turn off light (I guess) because without this call. The overlays will be effected by light.

**Comment by Vectrobe** [comment]
try removing the enableLighting and enableAlpha lines, they shouldn't be needed as neither the sky nor framebuffer stages use them. Technically you shouldn't need to disable them at the start either as I'm pretty sure they're already disabled in the last world render event...
